#####################################################
#   生成libCommon.a
#   author: jarek

ProjectDir=../../
include ../Make/MakeCommon.mk

LibName=libEngine.a
Inc=$(IncSelf)

include ../Make/MakeStaticLibrary.mk

