#####################################################
# 	生成test
#	author: jarek

ProjectDir=../../..
include ../../Make/MakeCommon.mk

BinDir=./
ExeName=EnumTest
ExternLib=
MyLib=$(LibEngine)
Inc=$(IncEngine) $(IncSelf)

include ../../Make/MakeExecutable.mk