#####################################################
#   生成libCommon.a
#   author: jarek

ProjectDir=../../
include ../Make/MakeCommon.mk

LibName=libCommon.a
Inc=$(IncSelf) $(IncEngine) $(IncProtocol)

include ../Make/MakeStaticLibrary.mk

